"""Harness H5: durable workflow event log.

Additive table for the harness event bus (Hendrixer bus.ts parity):

- ``workflow_events`` - append-only timeline per workflow (id identity
  sequence, workflow_id, type, JSONB payload, epoch created_at) plus an
  index on workflow_id for timeline reads.

Payloads are metadata only (names, ids, statuses); the bus only persists
events carrying a workflow_id, so ambient MCP chatter never lands here.

Guarded on information_schema like earlier revisions so fresh databases
whose lifespan ``create_all`` already built the table skip cleanly.

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-25

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _has_table(bind, table: str) -> bool:
    row = bind.execute(
        sa.text(
            "SELECT 1 FROM information_schema.tables "
            "WHERE table_schema = 'public' AND table_name = :t"
        ),
        {"t": table},
    ).first()
    return row is not None


def _has_index(bind, table: str, name: str) -> bool:
    row = bind.execute(
        sa.text(
            "SELECT 1 FROM pg_indexes "
            "WHERE schemaname = 'public' AND tablename = :t "
            "AND indexname = :n"
        ),
        {"t": table, "n": name},
    ).first()
    return row is not None


def upgrade() -> None:
    bind = op.get_bind()
    if not _has_table(bind, "workflow_events"):
        bind.execute(sa.text(
            "CREATE TABLE workflow_events ("
            " id BIGINT GENERATED BY DEFAULT AS IDENTITY,"
            " workflow_id TEXT NOT NULL,"
            " type TEXT NOT NULL,"
            " payload JSONB NOT NULL,"
            " created_at DOUBLE PRECISION NOT NULL,"
            " CONSTRAINT pk_workflow_events PRIMARY KEY (id)"
            ")"
        ))
    if _has_table(bind, "workflow_events") and not _has_index(
        bind, "workflow_events", "idx_workflow_events_workflow"
    ):
        bind.execute(sa.text(
            "CREATE INDEX idx_workflow_events_workflow"
            " ON workflow_events (workflow_id)"
        ))


def downgrade() -> None:
    bind = op.get_bind()
    if _has_index(bind, "workflow_events", "idx_workflow_events_workflow"):
        bind.execute(sa.text("DROP INDEX idx_workflow_events_workflow"))
    if _has_table(bind, "workflow_events"):
        bind.execute(sa.text("DROP TABLE workflow_events"))
